import "server-only";
import { prisma } from "@/lib/prisma";
import { addDays, toISODate } from "@/lib/date";
import { formatDate } from "@/lib/format";
import { nextRunDate } from "@/lib/billing-interval";
import { notify, getOrgAdminUserIds } from "@/lib/notifications";
import { sendAlert } from "@/lib/alerts";
import { invoiceableTimeWhere } from "@/lib/services/timesheets";
import { generateInvoice } from "@/lib/services/invoices";
import { autoSendInvoice } from "@/lib/services/invoice-delivery";
import type { ClientBillingCycle, PaymentTerms } from "@/generated/prisma/client";

const TERMS_DAYS: Record<Exclude<PaymentTerms, "CUSTOM">, number> = {
  DUE_ON_RECEIPT: 0,
  NET15: 15,
  NET30: 30,
  NET45: 45,
  NET60: 60,
  NET90: 90,
};

export type BillingCycleRunResult = {
  cycleId: string;
  ok: boolean;
  invoiceId?: string;
  note?: string;
};

/** Bills one client for everything unbilled dated before `cutoff` (a run
 * date at local midnight). Returns null when there was nothing to bill. */
async function billClient(cycle: ClientBillingCycle, cutoff: Date, now: Date) {
  // @db.Date columns are stored as UTC midnight of their calendar day.
  const cutoffDay = new Date(Date.UTC(cutoff.getFullYear(), cutoff.getMonth(), cutoff.getDate()));
  const projectScope = { clientId: cycle.clientId, orgId: cycle.orgId };

  const { timesheetApproval } = await prisma.organization.findUniqueOrThrow({
    where: { id: cycle.orgId },
    select: { timesheetApproval: true },
  });

  const [entries, milestones, expenses] = await Promise.all([
    prisma.timeEntry.findMany({
      where: {
        orgId: cycle.orgId,
        billable: true,
        invoiceLineItemId: null,
        date: { lt: cutoffDay },
        project: projectScope,
        // Unapproved weeks wait for the next run.
        AND: [invoiceableTimeWhere(cycle.orgId, timesheetApproval)],
      },
      select: { id: true },
    }),
    prisma.milestone.findMany({
      where: { invoiceLineItemId: null, completedAt: { not: null, lt: cutoff }, project: projectScope },
      select: { id: true },
    }),
    prisma.expense.findMany({
      where: {
        invoiceLineItemId: null,
        status: "APPROVED",
        incurredAt: { lt: cutoffDay },
        project: projectScope,
      },
      select: { id: true },
    }),
  ]);
  if (entries.length + milestones.length + expenses.length === 0) return null;

  const org = await prisma.organization.findUniqueOrThrow({ where: { id: cycle.orgId } });
  // A scheduled run has no logged-in actor; act as the org's owner, who can
  // see every project (including confidential ones).
  const owner = await prisma.membership.findFirstOrThrow({
    where: { orgId: cycle.orgId, role: "OWNER" },
    orderBy: { createdAt: "asc" },
  });

  const terms = cycle.paymentTerms === "CUSTOM" ? "NET30" : cycle.paymentTerms;
  const invoice = await generateInvoice(
    { orgId: org.id, defaultCurrency: org.defaultCurrency, actorId: owner.userId, role: "OWNER" },
    {
      clientId: cycle.clientId,
      timeEntryIds: entries.map((e) => e.id),
      milestoneIds: milestones.map((m) => m.id),
      expenseIds: expenses.map((e) => e.id),
      issueDate: toISODate(now),
      dueDate: toISODate(addDays(now, TERMS_DAYS[terms])),
      paymentTerms: terms,
      taxRate: Number(org.defaultTaxRate),
      notes: `Services through ${formatDate(addDays(cutoffDay, -1))}.`,
    }
  );

  const withClient = await prisma.invoice.findUniqueOrThrow({
    where: { id: invoice.id },
    include: { client: true },
  });

  if (cycle.autoSend) {
    // Emails the client and marks it sent; if it can't be emailed it's still
    // marked sent and the org is alerted.
    await autoSendInvoice(org.id, invoice.id, "billing cycle");
  } else {
    const message = `Invoice ${withClient.number} for ${withClient.client.name} was generated by its billing cycle as a draft — review and send.`;
    await sendAlert({
      orgId: org.id,
      event: "RECURRING_INVOICE_GENERATED",
      message,
      link: `/invoices/${invoice.id}`,
    });
  }

  return invoice;
}

/** Runs every billing cycle whose run date has arrived. A cycle that missed
 * several runs (e.g. the server was down) bills once, up to its most recent
 * run date, then moves on to the next future one. */
export async function runDueBillingCycles(now = new Date()): Promise<BillingCycleRunResult[]> {
  const due = await prisma.clientBillingCycle.findMany({
    where: { active: true, nextRunAt: { lte: now } },
  });

  const results: BillingCycleRunResult[] = [];
  for (const cycle of due) {
    let cutoff = cycle.nextRunAt;
    for (
      let n = nextRunDate(cutoff, cycle.interval, cycle.anchorDay);
      n <= now;
      n = nextRunDate(n, cycle.interval, cycle.anchorDay)
    ) {
      cutoff = n;
    }

    // Claim the run by advancing nextRunAt first, conditional on it being
    // unchanged — two overlapping job runs can't both bill the same period.
    const claimed = await prisma.clientBillingCycle.updateMany({
      where: { id: cycle.id, nextRunAt: cycle.nextRunAt },
      data: { nextRunAt: nextRunDate(cutoff, cycle.interval, cycle.anchorDay), lastRunAt: now },
    });
    if (claimed.count === 0) continue;

    try {
      const invoice = await billClient(cycle, cutoff, now);
      const note = invoice ? null : "Nothing unbilled — no invoice created.";
      await prisma.clientBillingCycle.update({
        where: { id: cycle.id },
        data: { lastInvoiceId: invoice?.id ?? null, lastRunNote: note },
      });
      results.push({ cycleId: cycle.id, ok: true, invoiceId: invoice?.id, note: note ?? undefined });
    } catch (err) {
      const note = `Failed: ${err instanceof Error ? err.message : String(err)}`;
      await prisma.clientBillingCycle.update({
        where: { id: cycle.id },
        data: { lastInvoiceId: null, lastRunNote: note },
      });
      // The unbilled items stay unbilled, so the next run picks them up.
      await notify(prisma, {
        orgId: cycle.orgId,
        userIds: await getOrgAdminUserIds(prisma, cycle.orgId),
        type: "RECURRING_INVOICE_GENERATED",
        message: `A scheduled invoice couldn't be generated (${note}). Unbilled work rolls into the next run.`,
        link: `/clients/${cycle.clientId}`,
      });
      results.push({ cycleId: cycle.id, ok: false, note });
    }
  }
  return results;
}
